// <auto-generated />
using Blood_Bank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blood_Bank.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231225224814_MigrationName")]
    partial class MigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blood_Bank.Core.Entities.Donations", b =>
                {
                    b.Property<int>("idDonation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonation"), 1L, 1);

                    b.Property<int>("idDonor")
                        .HasColumnType("int");

                    b.Property<int>("idSick")
                        .HasColumnType("int");

                    b.Property<int>("statusDonation")
                        .HasColumnType("int");

                    b.HasKey("idDonation");

                    b.ToTable("DonationsList");
                });

            modelBuilder.Entity("Blood_Bank.Core.Entities.Donors", b =>
                {
                    b.Property<int>("idDonor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idDonor"), 1L, 1);

                    b.Property<string>("fNameDonor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lNameDonor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pelephoneDonor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("statusDonor")
                        .HasColumnType("int");

                    b.Property<string>("typeBloodDonor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idDonor");

                    b.ToTable("DonorsList");
                });

            modelBuilder.Entity("Blood_Bank.Core.Entities.Sicks", b =>
                {
                    b.Property<int>("idSick")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idSick"), 1L, 1);

                    b.Property<string>("fNameSick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lNameSick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pelephoneSick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("statusSick")
                        .HasColumnType("int");

                    b.Property<string>("typeBloodSick")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idSick");

                    b.ToTable("SicksList");
                });
#pragma warning restore 612, 618
        }
    }
}
